
version: '3.2'

networks:
    samahara:
        external: 
            name: samahara

services:

    ca_org3:
        networks:
            samahara:
                aliases:
                    - ca_org3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == psq-Vostro-3653
        image: hyperledger/fabric-ca:x86_64-1.1.0
        hostname: ca.org3.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org3
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/00bcc2ab8317b25a4494587efac71720eb2671ccbebc0123fff542ee6835c6a1_sk
        ports:
            - 9054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
            
    cli_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == psq-Vostro-3653
        image: hyperledger/fabric-tools:x86_64-1.1.0
        tty: true
        hostname: cli_org3
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli.org3.example.com
          - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
          - CORE_PEER_LOCALMSPID=Org3MSP
          - CORE_CHAINCODE_KEEPALIVE=10
          - CORE_PEER_TLS_ENABLED=true
          - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.crt
          - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/server.key
          - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
          
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/chaincode:/opt/gopath/src/github.com/chaincode
            - /var/mynetwork/fabric-src/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
            - /var/mynetwork/certs/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - /var/mynetwork/certs/config:/var/hyperledger/config
            - /var/mynetwork/bin/:/var/bin
            # - /var/mynetwork/bin/jq:/usr/local/bin/jq
        networks:
            - samahara

    couchdb0_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == psq-Vostro-3653
        image: hyperledger/fabric-couchdb:x86_64-0.4.6
        hostname: couchdb0_org3
        networks:
           - samahara

    couchdb1_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == psq-Vostro-3653
        image: hyperledger/fabric-couchdb:x86_64-0.4.6
        hostname: couchdb1_org3
        networks:
           - samahara
